### ISSUE TITLE
spm logs

### ISSUE THREAD

**Issue by saiki-proof** [Jahn16/pspm#3]
There's just a few logs for the command... I want to trackdown the current processes from the binary

- [x] Init
- [x] Install
- [x] Add
- [x] Remove
- [x] Run
- [x] Update

**Comment by Jahn16** [comment]
I am working on improving the console output:
- [ ] Init 
- [ ] Install
- [ ] Add
- [ ] Remove
- [ ] Run
- [ ] Update

**Comment by Jahn16** [comment]
In the next release logs are much improved
